### ISSUE TITLE
Rework rustc driver

### ISSUE THREAD

**Issue by xFrednet** [rust-marker/marker#35]
The rustc driver tested out several ways how an AST can be translated and how callbacks can be implemented. Now that some progress has been made on #8 we have an almost set API for how lint crates and drivers communicate.

The next step is now to restructure or rewrite the rustc driver to be maintainable and follow this new API.

Goals:
* [x] Implement a clear structure
* [ ] Document the structure
* [x] Improve maintainability
* [x] Add caching (Even if minimal)
* [x] Improve lifetime structure
	* This can still be improved but is already way better :)

**Comment by xFrednet** [comment]
The structure first implemented as part of this issue has already improved the conversion process. However, after adding further nodes to the API and adding more conversion code, some limitations came up. For this reason, I'll once again try to restructure the driver code. The goal is to:
* [ ] Have consistent naming conventions (Currently, there are functions similar functions starting with different prefixes `to_`, `to_api`, `conv_`)
* [ ] Avoid passing `cx` around everywhere, I'll most likely use a single conversion struct for everything
* [ ] Define how the translation layer should usually be structure
* [ ] Cleanup lifetimes, mostly avoiding `'hir` if it's not needed
* [ ] Change location of the `Storage` struct
* [ ] Cut clear boundaries, where conversion functions should be located

And probably other things I can't think off rn. This comment is basically a new start for this issue.
